### ISSUE TITLE
Add support for Google Search Console

### ISSUE THREAD

**Issue by timbocode** [ClassicPress-research/classicpress-seo#16]
As per forum discussion https://forums.classicpress.net/t/classicpress-seo-experimental-plugin-now-available-for-testing-feedback/1652/38

**Comment by timbocode** [comment]
Experimental support added in release 0.4.0

**Comment by timbocode** [comment]
Leaving this open in the hope that someone is able to provide some feedback.

**Comment by ZigPress** [comment]
Search console connection works great. I have now deployed Classic SEO 0.4.4 on two sites:

www.zigpress.com
www.philippinestories.com

and I was able to link to Search Console without a problem.

The only issue I found was that the search console page within Classic SEO didn't find the sitemaps that I had previously submitted to Google.

**Comment by timbocode** [comment]
Thanks for the feedback. Will investigate.

**Comment by timbocode** [comment]
I've been having a look at this but couldn't find any real issue. The only thing I did note is that sometimes you need to hit the "Refresh Sitemaps" button on the Sitemaps tab. Does that work for you at all?

![image](https://user-images.githubusercontent.com/4199514/71113852-67fb8700-21c6-11ea-99a8-0d899b8063ee.png)

**Comment by ZigPress** [comment]
It seems maybe there's a delay before the search console API will 'release' the sitemaps to remote API calls. Certainly they are working now when I click refresh sitemaps (clicking that didn't work before when I had just submitted them).

**Comment by timbocode** [comment]
There can be lags in fetching data using the API and I know that GSC takes some time to process new sitemaps so this is perhaps expected behaviour. I checked Rank Math and that works in the same way. Clicking on the "Update cache manually" button in General Settings -> Search Console may help.

Are you OK if I close this issue as I think this is a limitation of the API more than anything? You can always reopen it (or create a new one) if it causes any problems.

**Comment by ZigPress** [comment]
Sure, OK to close. Thanks.

**Comment by timbocode** [comment]
Thanks.
