### ISSUE TITLE
Error when updating plugin

### ISSUE THREAD

**Issue by timbocode** [ClassicPress-research/classicpress-seo#19]
A message similar to the following is obtained after updating the Classic SEO plugin via the GitHub Updater:

`The plugin classicpress-seo-master/classicpress-seo.php has been deactivated due to an error: Plugin file does not exist`

Reported on the forums. See https://forums.classicpress.net/t/classic-seo-issue-editing-snippet-title/1727

**Comment by bahiirwa** [comment]
Did the plugin change the way it is served? I see “master” on the folder this was probably downloaded direct from GitHub. If the update changes the plugin folder, this error is probable.

**Comment by timbocode** [comment]
Yes, @bahiirwa thanks for the comment. I'm sure it's because the zip file extracts to `classicpress-seo-master` whereas most installation folders are just `classicpress-seo`. I haven't looked into this yet but if you know how to get the zip to extract to just `classicpress-seo`, I'd be grateful for some advice.

**Comment by bahiirwa** [comment]
Would be good to find out from CP how the migration plugin releases are done. They come with a custom zip file name. 

However, there is another hack. This is what I have found so far. https://stackoverflow.com/a/23642622/6773883.

**Comment by timbocode** [comment]
Thanks for the link. That looks very similar to what we've had to do with Installatron. Looks good as a workaround but as you say, it'd be good to know if there's a "proper" way to do it. I'll tag @nylen to see if he can throw any light on it.

**Comment by zulfgani** [comment]
The zip file is added manually when creating a release point, at least that's what I do with my repos. I then reference that url in the updater plugin.

**Comment by timbocode** [comment]
I have a few releases for Classic SEO. For example: https://github.com/ClassicPress-research/classicpress-seo/archive/v0.3.2.zip. However, this still extracts to `classicpress-seo-0.3.2` and not just `classicpress-seo`.

**Comment by zulfgani** [comment]
You want to do is encourage user to download "a named zip" file from the releases page rather than the main download link of the repo. This will eliminate the issue for those who do not change the plugin folder name to remove the -master or the version tag.

Create a zip file of the latest version named `classicpress-seo` and then when creating a release point you'd upload this zip in the given field (see screenshot) marked "Attach binaries by dropping....."
![Screenshot](https://user-images.githubusercontent.com/48245964/69486149-b70d0100-0e40-11ea-9911-220aa1d54e61.png)

Once the release is saved, in your Assets you'll have 3 items (the 2 source + the named zip) just as you see on the Migrate plugin. The named zip is the one that should be linked to when giving the download link out to users.

GitHub updater already strips out the added -master or version tag so there should be no issue when updating the plugin.

**Comment by timbocode** [comment]
Thanks very much for this @zulfgani . I'd never thought of doing it that way. I just assumed that GitHub had some hidden magic that I was missing.

So would you recommend keeping the name of the zip the same for each release, regardless of version number. For example, name it `classicpress-seo.zip` (or whatever) and keep that name for each release / upload? 

And as far as GitHub Updater goes, just to confirm, there's nothing I need to change? That will download `classicpress-seo-master.zip` each time and remove the `-master` part automatically? Genius.

**Comment by zulfgani** [comment]
You are welcome @timbocode.

It's a yes for both questions as that is what I'm doing [here](https://github.com/zulfgani/featherlite-controls/releases). Both releases have the same named-zip file in the assets so a user downloading from the latest release will always get the latest version as urls are different for both by the addition of the release tag version.

**Comment by timbocode** [comment]
Brilliant. Thanks @zulfgani

**Comment by xxsimoxx** [comment]
Fastest way to generate the zip file is using
`git archive -o "myplugin.zip" HEAD` 
in the root folder of a plugin.

I found useful using [hub](https://hub.github.com) to draft a release attaching the zip file.
`hub release create -d -a "myplugin.zip" -m "v1.2.3" "v1.2.3"`

**Comment by timbocode** [comment]
Thanks for this @xxsimoxx . That hub extension looks interesting. I'll give it a try.

**Comment by timbocode** [comment]
Closing this issue. No further reports of problems when updating. Comments / suggestions above helped resolve this. Also intend to switch to the CodePotent Update Manager. See #29
