### ISSUE TITLE
Breadcrumbs not displaying

### ISSUE THREAD

**Issue by timbocode** [ClassicPress-research/classicpress-seo#2]
As reported by @zulfgani on the forums:

In trying to add the breadcrumbs support to my theme via the template function I get no result although the shortcode works.

Digging through it appears the template-tags.php file is not being loaded thus rendering the function `cpseo_the_breadcrumbs();` non-existent.

**Comment by nylen** [comment]
When reports get split across different systems it's a good idea to add cross-links for future reference: https://forums.classicpress.net/t/classicpress-seo-experimental-plugin-now-available-for-testing-feedback/1652/3

**Comment by timbocode** [comment]
Thanks James. Yes, makes perfect sense.

**Comment by timbocode** [comment]
Fixed. Missing dependency in composer.json.
