### ISSUE TITLE
Bug with PHP <7 - plugin is not deactivated

### ISSUE THREAD

**Issue by xxsimoxx** [ClassicPress-research/classicpress-seo#20]
When activating with lower version of PHP the error message is correctly displayed, but the plugin is not deactivated.

The problem seems [here](https://github.com/ClassicPress-research/classicpress-seo/blob/fbf9a446d4105adb5de3e1de3f6197b69d653239/classicpress-seo.php#L230).

Just replacing `CPSEO_FILE` with `__FILE__` solves it.

**Comment by timbocode** [comment]
Thanks @xxsimoxx . Yes, of course, `CPSEO_FILE` is defined after it is called so that's not going to work too well is it? :) 

Thanks for reporting this. I'll create a fix shortly.

**Comment by timbocode** [comment]
Fixed in release 0.3.3
