### ISSUE TITLE
Add ability to import from All In One SEO

### ISSUE THREAD

**Issue by timbocode** [ClassicPress-research/classicpress-seo#28]
As per discussions on the forums (https://forums.classicpress.net/t/classic-seo-import-from-all-in-one-seo/1833), the ability to import from AIOSEO would be a useful feature to have. The absence of this feature is likely to deter AIOSEO users from switching to Classic SEO.

**Comment by nylen** [comment]
We have a bot that leaves a comment on a GitHub issue whenever it is mentioned on the forums. Would this be useful to enable for the ClassicPress-research projects too?

**Comment by timbocode** [comment]
Yes please James. I think it would.

**Comment by nylen** [comment]
I added this configuration, however, it will only apply to pull requests and commit comments (not issues) u

**Comment by nylen** [comment]
Sorry, didn't mean to close.

**Comment by timbocode** [comment]
Thanks James.

**Comment by timbocode** [comment]
Reopened following [this report](https://forums.classicpress.net/t/classic-seo-0-5-0-release/1864/2) from the forums:

1. I found that the AIOSEO import pulled in post title and post description without a problem. 
2. It imported the AIOSEO post keywords as focus keywords which is probably the closest equivalent.
3. It didn’t pull in all general settings - for example, **it pulled in the title format with a custom separator for categories but not for pages or posts.**
4. It did pull in some schema data for local search.

**Initial response:**
1. Seems OK
2. Seems OK but needs a quick check
3. This is the main issue. Needs a full investigation
4. Seems OK but needs a quick check

**Comment by timbocode** [comment]
Hopefully fixed in release 0.5.1. Awaiting feedback.

**Comment by timbocode** [comment]
Further improvements in release 0.5.2 and 0.5.3. AIOSEO deprecated some variables / macros which has been the source of much fun. Not. Hopefully, version 0.5.3 should resolve any outstanding issues.

**Comment by timbocode** [comment]
Closing this now. No further reports.
