### ISSUE TITLE
Feature request: use CodePotent Update Manager for updates

### ISSUE THREAD

**Issue by zigpress** [ClassicPress-research/classicpress-seo#29]
This is a non-urgent feature request.

I've found that most of the time, the Github Updater does not show when an update for Classic SEO is available, and the update has to be done manually.

A different method is available, which doesn't require an additional plugin to be installed alongside Classic SEO. It does however require a PHP class to be added to the plugin, and it requires the 'host' CP installation (which will report updates) to have the Update Manager installed and configured.

https://codepotent.com/classicpress/plugins/update-manager/

This might be a more reliable solution until the CP plugin directory is implemented in the future.

**Comment by johnalarcon** [comment]
Just a heads up that Update Manager RC2 is being finalized right now... and will probably be declared the stable version (if no critical issues roll in.) It contains a breaking change from Update Manager RC1, so, it's not recommended to use RC1 for anything other than lining birdcages going forward. :)

**Comment by johnalarcon** [comment]
Update Manager RC2 is [available for download](https://github.com/codepotent/Update-Manager/releases/tag/1.0.0-rc2). If you decide to give it a try with ClassicPress SEO, let me know your thoughts. Thanks!

**Comment by timbocode** [comment]
I'll definitely be giving it a try John. In fact, I downloaded a copy earlier via your post on the forums so it's in the pipeline :)

**Comment by timbocode** [comment]
Closed by #44
