### ISSUE TITLE
Word count not being processed properly

### ISSUE THREAD

**Issue by ZigPress** [ClassicPress-research/classicpress-seo#30]
See screenshot below - the word count is 587 but it still gives a cross and asks for at least 500 words.

![Screen Shot 2019-12-21 at 11 18 53](https://user-images.githubusercontent.com/9252339/71302237-d9645100-23e3-11ea-81d3-ff4248067ae6.png)

**Comment by timbocode** [comment]
Fixed in release 0.5.3
