### ISSUE TITLE
Minimum PHP version

### ISSUE THREAD

**Issue by xxsimoxx** [ClassicPress-research/classicpress-seo#39]
Running `phpcs` I've seen that the code is fully compatible with PHP 5.6.

Is it ok to enforce PHP 7 as a minimum version?

**Comment by timbocode** [comment]
Yes, I think it's OK. I know that Classic SEO currently works on PHP 5.6 but that's not a road I want to go down. By making the minimum PHP version 7.x, it means I can dump outdated PHP methods and utilise new ones and that's something I will be looking at after 1.0 is released.

I also don't have the time or resources to test and support Classic SEO on unsupported versions of PHP so I'm happy to leave the minimum PHP requirement as 7.x.

PHP 5.6 was already EOL when the first public release of Classic SEO was made. Even PHP 7.2 is now in the "Security fixes only" stage.

After all, the minimum PHP requirements for ClassicPress itself is likely to be 7.x in the next major release.

**Comment by timbocode** [comment]
Are you OK if I close this?

**Comment by timbocode** [comment]
One other thing @xxsimoxx would you be able to share your PHPCS tests? That would be a big help.

**Comment by xxsimoxx** [comment]
Yes, I'm ok to close!

## PHPCS
I'm checking only php because of warnings for minified files.
`phpcs -p . --extensions=php --standard=PHPCompatibility --runtime-set testVersion X.Y`
### Version 5.6
clean
### Version 7.0 to 7.4:
Only a warn about CMB2, that *seems to me* not creating problems.
```
FILE: ...tent/plugins/classicpress-seo/vendor/cmb2/includes/CMB2_Base.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 417 | WARNING | Since PHP 7.0, functions inspecting arguments, like
     |         | func_get_args(), no longer report the original value
     |         | as passed to a parameter, but will instead provide
     |         | the current value. The parameter "$message" was
     |         | used, and possibly changed (by reference), on line
     |         | 416.
----------------------------------------------------------------------
```

**Comment by timbocode** [comment]
Thanks Simone.
