### ISSUE TITLE
Add support for Classic Commerce

### ISSUE THREAD

**Issue by timbocode** [ClassicPress-research/classicpress-seo#9]
As per existing support for WooCommerce

**Comment by bahiirwa** [comment]
Does this relate to #26 ?

**Comment by timbocode** [comment]
Yes it does. I've left them as two separate issues as #9 (this one) is more concerned with integration with CC whereas #26 is purely about detection. Classic SEO already supports WC and on the quick tests I've done, seems to support CC pretty well too.

**Comment by timbocode** [comment]
Closing this now. Seems to be working well through various recent releases of Classic Commerce and have received no reports to the contrary.
